// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5G_2yVFfjN81qQCLzHHo4x2mhciOoYUs',
    appId: '1:259224209333:web:ceafe89302f05946d1bbfc',
    messagingSenderId: '259224209333',
    projectId: 'skola-ecef2',
    authDomain: 'skola-ecef2.firebaseapp.com',
    storageBucket: 'skola-ecef2.appspot.com',
    measurementId: 'G-9YY14LYCM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC57-KI-xczzYADKx63LsXwjuif8soqESc',
    appId: '1:259224209333:android:c7860188a1ba8183d1bbfc',
    messagingSenderId: '259224209333',
    projectId: 'skola-ecef2',
    storageBucket: 'skola-ecef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFfIlxFsfApHv4cN4PjZr28H76R3GaIXw',
    appId: '1:259224209333:ios:ce8ab1a175853a41d1bbfc',
    messagingSenderId: '259224209333',
    projectId: 'skola-ecef2',
    storageBucket: 'skola-ecef2.appspot.com',
    iosClientId: '259224209333-qodq5qskbcf3rjoh19qbipidd7cmimio.apps.googleusercontent.com',
    iosBundleId: 'com.example.rasporedi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFfIlxFsfApHv4cN4PjZr28H76R3GaIXw',
    appId: '1:259224209333:ios:ce8ab1a175853a41d1bbfc',
    messagingSenderId: '259224209333',
    projectId: 'skola-ecef2',
    storageBucket: 'skola-ecef2.appspot.com',
    iosClientId: '259224209333-qodq5qskbcf3rjoh19qbipidd7cmimio.apps.googleusercontent.com',
    iosBundleId: 'com.example.rasporedi',
  );
}
